### PR TITLE
1.1.2

### PR DESCRIPTION
**Pull request by gbalabasquer**

### CODE REVIEW

**Comment by gbalabasquer** [comment]
Abis and link to change still pending to be done.

**Review by zdumitru — APPROVED** [review]

**Comment by gbalabasquer** [comment]
PR is now complete, so final review can be done.

**Review by kmbarry1 — APPROVED** [review]
LGTM

New mainnet addresses seem correct.

**Comment by gbalabasquer** [comment]
@zdumitru if you can give a new approval so we can merge would be nice. Spell is already being voted.

**Review by zdumitru — APPROVED** [review]

**Comment by gbalabasquer** [comment]
Thank you!

**Pull request merged**
