### PR TITLE
Add abis for 1.1.4

### PR DESCRIPTION
**Pull request by gbalabasquer**

### CODE REVIEW

**Comment by gbalabasquer** [comment]
Still missing the IPFS urls.

**Comment by gbalabasquer** [comment]
@brianmcmichael ^^

**Comment by gbalabasquer** [comment]
IPFs addresses added. Ready to be reviewed.

**Review by zdumitru — APPROVED** [review]

**Comment by kmbarry1** [comment]
My general comment here is that this is not very "reviewable" for a human...I trust that it was done correctly, or at least that there was an intention for that...but it's not feasible to review every ABI by hand. Probably should automate this eventually.

**Review by kmbarry1 — APPROVED** [review]

**Pull request merged**
