### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by zdumitru**
following #99 PR, we didn't add links to the main page.

### CODE REVIEW

**Comment by gbalabasquer** [comment]
Hmm not sure about the dates. 1.2.0 has been active in kovan since last week but the spell hasn't even created yet in mainnet.

**Comment by zdumitru** [comment]
> Hmm not sure about the dates. 1.2.0 has been active in kovan since last week but the spell hasn't even created yet in mainnet.
> What do these dates want to express?

@gbalabasquer These are the dates when the contracts has been deployed. As per _Disclaimer 3_ on the main page they may not be in use yet or not used at all (if rejected in voting).

**Comment by gbalabasquer** [comment]
Then 1/12 is not correct as on mainnet the chief and vote proxy were deployed on Nov 25th and the spell was deployed today (2/12).
As it can happen that two different contracts that are being added in the same spell are deployed on different dates, I'd suggest we use the spell date.

Regarding kovan spell, it was deployed on November 25th as well.

**Comment by gbalabasquer** [comment]
@zdumitru Do you want to change the dates so we can merge? We should have the addresses published by this time.
The actual status is also a bit broken as in kovan there isn't `1.2.0` but you still access to it when clicking on `active`.

**Comment by zdumitru** [comment]
@gbalabasquer Updated the dates to deployment dates.

Isn't Kovan already deployed and in use? I thought it is, thus `active` link updated.

**Comment by gbalabasquer** [comment]
Yeah, it's fine, that's why I marked `1.2.0` as active in kovan. But what I mean is as I forgot to add `1.2.0` it remained in a weird status.

**Review by gbalabasquer — APPROVED** [review]
I'd still prefer to use the spell date as I have suggested, but if the other is the one that we want, then LGTM.

**Pull request merged**
